# Generated by Django 3.2.5 on 2021-07-09 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distribuidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Rams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('precio', models.IntegerField()),
                ('capacidad', models.CharField(max_length=70)),
                ('tipo', models.CharField(max_length=70)),
                ('frecuencia', models.CharField(max_length=70)),
                ('formato', models.CharField(max_length=70)),
                ('voltaje', models.CharField(max_length=70)),
                ('distribuidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.distribuidor')),
            ],
        ),
    ]
