# Generated by Django 3.2.5 on 2021-07-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rams',
            name='imagen',
            field=models.ImageField(null=True, upload_to='Rams'),
        ),
    ]
