# Generated by Django 3.2.5 on 2021-07-09 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rams_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('procesador', models.CharField(max_length=70)),
                ('memoria', models.CharField(max_length=70)),
                ('graficos', models.CharField(max_length=80)),
                ('almacenamiento', models.CharField(max_length=70)),
                ('caratula', models.ImageField(null=True, upload_to='games')),
                ('distribuidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.distribuidor')),
            ],
        ),
    ]
