# Generated by Django 3.2.5 on 2021-07-09 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_procesador'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('memoria', models.CharField(max_length=70)),
                ('frecuencia', models.CharField(max_length=70)),
                ('marca', models.CharField(max_length=70)),
                ('nucleos', models.CharField(max_length=70)),
                ('precio', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='Graficos')),
                ('distribuidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.distribuidor')),
            ],
        ),
    ]
